"""create admin table

Revision ID: 87030b96adf8
Revises: c4e4dc55f5ee
Create Date: 2026-04-16 13:49:59.683526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87030b96adf8'
down_revision = 'c4e4dc55f5ee'
branch_labels = None
depends_on = None


def upgrade():
    
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

   
    op.execute("""
        UPDATE admin
        SET
            email = "user".email,
            password = "user".password,
            is_active = "user".is_active
        FROM "user"
        WHERE admin.user_id = "user".id
    """)

    
    op.execute("UPDATE admin SET email = CONCAT('admin_', id, '@temp.com') WHERE email IS NULL")
    op.execute("UPDATE admin SET password = '123456' WHERE password IS NULL")
    op.execute("UPDATE admin SET is_active = true WHERE is_active IS NULL")

    
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('email', existing_type=sa.String(length=120), nullable=False)
        batch_op.alter_column('password', existing_type=sa.String(length=255), nullable=False)
        batch_op.alter_column('is_active', existing_type=sa.Boolean(), nullable=False)

  
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('admin_user_id_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('admin_user_id_fkey'), type_='foreignkey')
        batch_op.create_unique_constraint('uq_admin_email', ['email'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('admin_user_id_fkey'), 'user', ['user_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('admin_user_id_key'), ['user_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('is_active')
        batch_op.drop_column('password')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
